stages:
  - build
  - deploy

variables:
  IMAGE: sonnyrranger/task-app:latest

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

build:
  stage: build
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy:
  stage: deploy
  script:
    - echo "$KUBECONFIG_DATA" > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig
    - kubectl apply -f k8s/
